spring:
  datasource:
    url: jdbc:mariadb://192.168.1.227:3306/mingbang_db
    username: mingbang_db_user
    password: yx#MINGBANGDB_023
  thymeleaf:
    cache: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.demo.ssjo.mapper: debug

cfg:
  localPath: E:/IdeaProjects/DriverTraining_v1.0/web/upload/
  netPath: http://localhost:8085
